version: "3.9"
name: pysect-backend-notification-dev
services:

  web-dev:
    image: "simeonevilardo/pysect-backend-notification-dev"
    container_name: pysect-backend-notification-dev
    platform: linux/arm64/v8
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env.dev
    environment:
      VIRTUAL_HOST: py.sect.test.letz.dev
      VIRTUAL_PATH: ~^/(api/notification)/
      VIRTUAL_PORT: 8000
    command: ./docker/express/local_run.sh

networks:
  nginx-reverse-proxy-net:
    external: true